# VoiceFlow Comprehensive Testing Framework Configuration

# Test Orchestration Settings
orchestration:
  max_parallel_tests: 4
  default_timeout: 300
  output_directory: "test_results"
  enable_parallel_execution: true
  enable_performance_monitoring: true
  enable_coverage: true
  fail_fast: false
  retry_failed_tests: true
  max_retries: 2
  generate_html_report: true
  enable_real_time_monitoring: true
  test_data_cleanup: true

# Test Environment Configuration
environment:
  # Mock configurations for testing
  mock_audio_device: true
  mock_ai_service: true
  mock_system_integration: true
  
  # Test data paths
  test_data_dir: "test_data"
  temp_dir_prefix: "voiceflow_test_"
  
  # Database configuration for testing
  database:
    use_memory_db: true
    enable_encryption: false
    cleanup_after_tests: true

# Performance Testing Configuration
performance:
  # Benchmarks and thresholds
  benchmarks:
    audio_transcription_latency_ms: 2000
    ai_enhancement_latency_ms: 3000
    text_injection_latency_ms: 500
    database_write_latency_ms: 100
    memory_baseline_mb: 100
    memory_growth_per_hour_mb: 10
    transcriptions_per_minute: 20
    cpu_usage_percent: 50
  
  # Performance monitoring
  monitoring:
    sample_interval: 0.1
    enable_memory_profiling: true
    enable_cpu_profiling: true
    track_system_metrics: true
  
  # Regression testing
  regression:
    baseline_file: "performance_baseline.json"
    regression_threshold_percent: 10
    save_baseline_on_success: false

# Test Suite Configuration
test_suites:
  # Unit tests
  unit_tests:
    enabled: true
    timeout: 120
    parallel_safe: true
    priority: 1
    tags: ["unit", "fast"]
    
  # Integration tests
  integration_tests:
    enabled: true
    timeout: 300
    parallel_safe: true
    priority: 2
    tags: ["integration"]
    
  # End-to-end tests
  e2e_tests:
    enabled: true
    timeout: 600
    parallel_safe: false
    priority: 3
    tags: ["e2e", "slow"]
    
  # Performance tests
  performance_tests:
    enabled: true
    timeout: 900
    parallel_safe: false
    priority: 4
    tags: ["performance", "slow"]
    
  # Security tests
  security_tests:
    enabled: true
    timeout: 300
    parallel_safe: true
    priority: 2
    tags: ["security"]
    
  # Load tests
  load_tests:
    enabled: false  # Disabled by default due to resource intensity
    timeout: 1200
    parallel_safe: false
    priority: 5
    tags: ["load", "stress", "slow"]

# Test Data Configuration
test_data:
  # Audio test data
  audio:
    sample_rate: 16000
    channels: 1
    format: "wav"
    durations: [1, 3, 5, 10]  # seconds
    noise_levels: [0.1, 0.3, 0.5]
    
  # Text test data
  text:
    short_texts: 
      - "Hello world"
      - "Test recording"
      - "Quick note"
    medium_texts:
      - "This is a medium length test sentence."
      - "Testing voice recognition capabilities."
      - "Professional dictation example text."
    long_texts:
      - "This is a much longer test that simulates extended dictation sessions with complex content."
      - "Professional documentation requires accurate transcription of technical terminology and proper formatting."
    
  # AI enhancement test data
  ai_enhancement:
    test_prompts:
      - "fix grammar and punctuation"
      - "improve formatting and clarity"
      - "professional tone enhancement"
    expected_improvements:
      - "capitalization"
      - "punctuation"
      - "grammar"
      - "formatting"

# Reporting Configuration
reporting:
  # Output formats
  formats:
    json: true
    html: true
    text: true
    xml: false
    
  # Report content
  include_detailed_logs: true
  include_system_metrics: true
  include_performance_graphs: true
  include_error_details: true
  
  # Report distribution
  save_to_file: true
  email_reports: false
  webhook_notifications: false
  
  # Archive settings
  archive_old_reports: true
  archive_after_days: 30
  max_archived_reports: 100

# CI/CD Integration
ci_cd:
  # Jenkins integration
  jenkins:
    enabled: false
    build_status_file: "test_status.json"
    artifacts_dir: "test_artifacts"
    
  # GitHub Actions integration
  github_actions:
    enabled: false
    output_annotations: true
    set_status_checks: true
    
  # Quality gates
  quality_gates:
    min_success_rate: 95
    max_regression_count: 0
    max_critical_failures: 0
    min_coverage_percent: 80

# Advanced Configuration
advanced:
  # Debugging
  debug_mode: false
  verbose_logging: false
  save_debug_artifacts: false
  
  # Resource limits
  max_memory_usage_mb: 2048
  max_cpu_usage_percent: 80
  max_test_duration_hours: 2
  
  # Cleanup settings
  cleanup_temp_files: true
  cleanup_test_databases: true
  cleanup_log_files: false
  
  # Experimental features
  experimental:
    adaptive_timeouts: false
    smart_test_ordering: false
    predictive_failure_detection: false