name: Basic VoiceFlow Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  basic-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install basic dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml psutil
    
    - name: Run debug script
      run: |
        python debug_ci.py
    
    - name: Run basic test
      run: |
        python test_basic_ci.py
    
    - name: Test file structure
      run: |
        ls -la
        echo "Current directory: $(pwd)"
        echo "Python version: $(python --version)"
        echo "Files in current directory:"
        find . -name "*.py" | head -10